services:
  - type: web
    name: terabox-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: BOT_TOKEN
        sync: false   # तुम Render पर manually डालोगे
